FROM node:8.11.1 AS builder

# --------------------------------------
# Update npm
# --------------------------------------
RUN npm install npm@6.2.0 -g

# --------------------------------------
# Install Chrome for testing
# --------------------------------------
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update && apt-get install -y google-chrome-stable
