apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Name }}
    spec:
      containers:
      - name: msa-{{ .Values.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        resources:
{{ toYaml .Values.deployment.resources | indent 12 }}
        env:
          - name: MSA_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.Name }}-configmap
                key: MSA_ENVIRONMENT
          - name: MSA_RELEASE_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.Name }}-configmap
                key: MSA_RELEASE_NAME
          - name: MSA_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.Name }}-configmap
                key: MSA_ENDPOINT