apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80